### ISSUE TITLE
Open source consideration?

### ISSUE THREAD

**Issue by tutujingyugang1** [insait-institute/GenieRedux#1]
Your project is truly impressive. If I may ask, are there any plans regarding open-sourcing it?

**Comment by NSavov** [comment]
@tutujingyugang1 Thanks for the interest! We are busy with a deadline in a few weeks at the moment but we are planning to review and release the code afterwards.

**Comment by NSavov** [comment]
@tutujingyugang1 I am happy to announce that we have released our code. I hope that it is of use to you and others.
